/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\Floating Port.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Model } from "./IslandModel"

export default function Island(props) {
  return (
    <Model/>
  )
}

